version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    container_name: react-frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  server:
    build:
      context: ./server
    ports:
      - 3001:3001
    container_name: node-server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
  